# Generated by Django 3.2 on 2021-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='thumbnail', verbose_name='Thumbnail'),
        ),
    ]
