# Generated by Django 3.2 on 2021-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default-thumbnail.jpg', upload_to='thumbnail', verbose_name='Thumbnail'),
        ),
    ]
